### ISSUE TITLE
Support for scala 2.12.1

### ISSUE THREAD

**Issue by morpheyesh** [doriordan/skuber#56] opened 2017-05-19 16:03 UTC
Can I know when there will be support for scala 2.12

**Comment by morpheyesh** [comment] 2017-05-19 16:43
I see, iteratees-extras does not have 2.12 yet.

**Comment by doriordan** [comment] 2017-06-02 06:30
Scala 2.12 support is being actively looked at along with Play 2.5 (@amir has done some work at https://github.com/doriordan/skuber/pull/54). Not trivial and no ETA yet but it is a high priority.

**Comment by kojustin** [comment] 2017-06-15 00:54
I would really like this. What's left to do and how can I help? Is it just getting tests for #54 to pass?

**Comment by doriordan** [comment] 2017-06-15 09:03
It is really about the need to update the projects dependencies - in particular Play - to versions supported on Scala 2.12.

**Comment by amir** [comment] 2017-06-15 09:14
If you don't require to watch resources then you should be able to use #54. The reason that #54 is marked is WIP is that the watching need to be rewritten—there's also one marshalling test failing which is possibly a regression that I've to look into. I'm interested in finishing off #54 but not entirely sure when that'd be done.

**Comment by justinhj** [comment] 2017-07-20 22:51
+1

**Comment by doriordan** [comment] 2017-10-11 08:57
I've pushed a release_2.0 branch - this is basically an initial release candidate for Skuber V2.0 which has the following major changes:
- Supports Scala 2.12
- Now uses Akka Http client instead of Play 2.4 WS 
- Uses Akka streams instead of Play enumeratees/iteratees

So when this release is official it will resolve this issue - I will leave it open for now.
If anyone wants to give the new release a test run please go ahead and I'll be very interested in any feedback. You'll need some modest changes to your code around the init() and close() calls for the API (see examples / docs) but API requests themselves should be unchanged, unless you are using Watch API. Obviously you will need to change your build/deps as well for Scala 2.12.

**Comment by doriordan** [comment] 2017-11-13 08:19
Note that the changes for release 2.0 are now merged to master, so it is now the recommended version to use for new projects and has a quite well-tested pre-release (2.0.0 RC2) available.
I will close this issue when the full 2.0.0 release is published.

**Comment by doriordan** [comment] 2018-01-16 15:27
Skuber 2 has been released so closing this issue

**Closed by doriordan** 2018-01-16 15:27 UTC
Labels: enhancement, release 2
