### ISSUE TITLE
get pods error

### ISSUE THREAD

**Issue by fcastillao** [doriordan/skuber#183] opened 2018-07-30 20:07 UTC
i am running into what seems to be a deserialization error similar to: #175 and #149 

main error is:
Failed => akka.http.scaladsl.server.RejectionError

and previous message is:
[INFO] [07/30/2018 14:51:22.996] [main] [skuber.api] [ { reqId=641d2da9-c09d-4a41-9523-a3aec5e85b5b} } - about to send HTTP request: GET https://api.int-1-aws-eu-west-1.k8s.in.here.com/api/v1/namespaces/here-olp-notebook-here-sit/pods]
[INFO] [07/30/2018 14:51:24.755] [default-akka.actor.default-dispatcher-4] [skuber.api] [ { reqId=641d2da9-c09d-4a41-9523-a3aec5e85b5b} } - received response with HTTP status 200]
e => JsError(List((/items(3)/spec/volumes(2)/awsElasticBlockStore,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(2)/downwardAPI,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(2)/rbd,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(2)/secret,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(2)/configMap,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(2)/nfs,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(2)/iscsi,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(2)/hostPath,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(2)/emptyDir,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(2)/glusterfs,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(2)/persistentVolumeClaim,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(2)/gcePersistentDisk,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(2)/gitRepo,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(3)/awsElasticBlockStore,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(3)/downwardAPI,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(3)/rbd,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(3)/secret,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(3)/configMap,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(3)/nfs,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(3)/iscsi,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(3)/hostPath,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(3)/emptyDir,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(3)/glusterfs,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(3)/persistentVolumeClaim,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(3)/gcePersistentDisk,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(3)/spec/volumes(3)/gitRepo,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(2)/awsElasticBlockStore,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(2)/downwardAPI,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(2)/rbd,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(2)/secret,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(2)/configMap,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(2)/nfs,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(2)/iscsi,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(2)/hostPath,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(2)/emptyDir,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(2)/glusterfs,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(2)/persistentVolumeClaim,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(2)/gcePersistentDisk,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(2)/gitRepo,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(3)/awsElasticBlockStore,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(3)/downwardAPI,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(3)/rbd,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(3)/secret,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(3)/configMap,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(3)/nfs,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(3)/iscsi,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(3)/hostPath,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(3)/emptyDir,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(3)/glusterfs,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(3)/persistentVolumeClaim,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(3)/gcePersistentDisk,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/items(4)/spec/volumes(3)/gitRepo,List(JsonValidationError(List(error.path.missing),WrappedArray())))))

could this be some error on my side? or is similar indeed to the other issues?

thanks in advance

**Comment by ngortheone** [comment] 2018-07-31 00:53
@fcastillao can you describe your setup (skuber version, scala/java, k8s version, etc) and steps to reproduce?

**Comment by fcastillao** [comment] 2018-07-31 14:01
yes, sorry.

skuber version 2.0.9
scala version 2.12.4
java version "1.8.0_181"
k8s Server Version: Major:"1", Minor:"10", GitVersion:"v1.10.5"

steps to reproduce would be:

1. create the cluster, user, and context
2. create the Maps for clusters users and contexts
3. create the config
4. call k8sinit with the config
5. call the rest of the methods on the provided List example (https://github.com/doriordan/skuber/blob/master/examples/src/main/scala/skuber/examples/list/ListExamples.scala) 

`val dpCluster = K8SCluster("v1", CLUSTERURI, insecureSkipTLSVerify = true)
  val dpUser = TokenAuth(AUTHTOKEN)
  val dpContext = K8SContext(dpCluster, dpUser)
  val clusters = Map(CLUSTERNAME -> dpCluster)
  val contexts = Map(CONTEXTNAME -> dpContext)
  val users = Map(USERNAME -> dpUser)
  val directlyConfig = Configuration(clusters, contexts, dpContext, users)
  val k8s = k8sInit(directlyConfig)
  val ksysPods: Future[PodList] = k8s listInNamespace[PodList] (NAMESPACE)
  val printKSysPods = ksysPods map { podList => listPods(podList.items) }`

**Comment by ngortheone** [comment] 2018-07-31 14:04
I will try to reproduce it

**Comment by ngortheone** [comment] 2018-08-01 00:33
I have tested with minikube of the same version. 
I have valid `~/.kube/config` file and I replaced all configuration steps with
```
  val k8s = k8sInit(api.Configuration.parseKubeconfigFile().get)
```
and then I was able to run all examples successfully.

There think that the following scenarios are possible:
* The most likely scenario - a problem somewhere in your configuration. (everything inside `directlyConfig `) - and error`akka.http.scaladsl.server.RejectionError` supports that theory
* Less likely - some specific workload types that do not get parsed correctly. The way to verify that is to kill everything from your cluster so only stuff in `kube-system` is left and try running examples again. And indication of that would be a different (meaning - successful on empty cluster) result.

**Comment by fcastillao** [comment] 2018-08-01 14:25
thanks for your answer and time :) 
it would seem like you are right, perhaps is something related with configuration:

the file i use to run kubectl commands throws me an exeption when trying to use it with Skuber 
this seems related to the "insecure-skip-tls-verify: true" flag, as NOT putting it in the config file will give me some certs exeptions.

and putting it in the config file will no longer throw said exeption but will throw the previous error, and i am no longer to run kubectl commands with the error "specifying a root certificates file with the insecure flag is not allowed"

so there must be some kind of special configuration needed for the authentication with my K8S cluster.

but validating the second scenario is not possible as im not authorized to access other namespaces besides my own.

i will keep looking into the issue.

thanks a lot @ngortheone

**Comment by ngortheone** [comment] 2018-08-01 14:45
@fcastillao also keep in mind that [examples](https://github.com/doriordan/skuber/blob/master/examples/src/main/scala/skuber/examples/list/ListExamples.scala) explicitly querying your current namespace and `kube-system`
here: https://github.com/doriordan/skuber/blob/master/examples/src/main/scala/skuber/examples/list/ListExamples.scala#L56

and so if you say that 
> im not authorized to access other namespaces besides my own.
this on its own can be the cause of the problem. Try modifying examples to exclude `kube-system` and leave only your namespace

**Comment by fcastillao** [comment] 2018-08-01 15:13
oh yes, i did so the only namespace im trying to query is my own haha

**Comment by doriordan** [comment] 2018-08-02 10:26
I suspect the unmarshalling issue above is that one of the pods in your cluster specifies a couple of volumes of some type(s) not yet supported by skuber.  I'll create an issue for the missing types up to v1.11.

**Comment by cgbaker** [comment] 2018-08-02 13:32
@doriordan , I'm glad this came up. It speaks to an issue that I'm dealing with right now. I was looking at leaving a pass-through payload capability for my users, so that I didn't have to keep a list of well-known volumes types and constantly translate those to the supported types in skuber. I thought I might just add a `GenericVolumeSource(blob: JsValue)`, but `Volume#Source` is currently sealed. Another approach is to simply overload the Read/Write at any place where a `Volume` could occur, but that's a lot of work.

Thoughts? I don't know what the plan is with k8s regarding new volume types; I had the impression at one point they were going to stop adding new ones and hand this over to the storage driver. But the ability of a new capability volume type to crash the parsing (esp as concerns Volume-adjacent classes like Pod), means that skuber isn't forward-compatible. This seems like something we should try to address.

**Comment by doriordan** [comment] 2018-08-02 15:10
@cgbaker Lets take this over to the new issue I created at #184

**Comment by fcastillao** [comment] 2018-08-08 16:13
as this is going to be taken to the new issue, feel free to close this one when you consider appropiate

**Comment by ngortheone** [comment] 2018-08-08 16:17
Hi @fcastillao, can you please close it since you were the one who opened it?

**Closed** 2018-08-08 19:31 UTC
