### ISSUE TITLE
Error using k8sConfig

### ISSUE THREAD

**Issue by charlesa101** [doriordan/skuber#137] opened 2018-05-08 05:44 UTC
I am trying to use my own configuration with `k8sInit` 

but i keep getting this exception

```
[com.typesafe.sslconfig.ssl.DefaultHostnameVerifier] - verify: Certificate does not match hostname! subjectAltNames = [[2, docker-for-desktop], [2, kubernetes], [2, kubernetes.default], [2, kubernetes.default.svc], [2, kubernetes.default.svc.cluster.local], [7, 10.96.0.1], [7, 192.168.65.3]], hostName = localhost Cause: java.security.cert.CertificateException: No subject alternative DNS name matching localhost found.
```

Any idea?

**Comment by agemooij** [comment] 2018-05-08 11:04
Looks like you are trying to use HTTPS (e.g. TLS, aka SSL) to connect to (a K8s proxy on) localhost, which is running a TLS endpoint with a certificate configured only for the hostnames listed while you are trying to reach it using the hostname `localhost`, which is not in the list.

So you probably either have to change the hostname you are connecting to (perhaps add an alias in `/etc/hosts`?) or you should connect to K8s using HTTP instead of HTTPS.

**Comment by charlesa101** [comment] 2018-05-08 13:50
@agemooij  yea i understand thats the issue how do i configure that here, currently reading up my kubeconfig via iostream and setting the current context to my minikube

```scala
val ioStream = new java.io.ByteArrayInputStream(kubeConfigStr.getBytes(java.nio.charset.Charset.forName("UTF-8")))
    val k8sConfig = K8SConfiguration.parseKubeconfigStream(ioStream).get
    val cc= k8sConfig.contexts.get("docker-for-desktop").get
    val context = k8sConfig.useContext(cc)
    implicit val k8s = k8sInit(context )
```

**Comment by Matt-Dee** [comment] 2018-10-17 12:33
I'm running into the same issue.

```bash
[ERROR] [10/17/2018 12:27:28.943] [default-akka.actor.default-dispatcher-4] [skuber.api] [ { reqId=a6dc5b5d-a72d-4619-8f46-a0da7f785098} } - HTTP request resulted in an unexpected exception ] (akka.stream.ConnectionException: Hostname verification failed! Expected session to be for spackler)

192.168.88.135 - - [17/Oct/2018:12:27:28 +0000] "GET /workflow/submit-ll-workflow/hadoop/0.05/0.90/ HTTP/1.1" 500 110 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:62.0) Gecko/20100101 Firefox/62.0" 103
```

I'm going through a configured ingress that is set up within K8s.

the ingress is configured:
wrkflw.svc.cmdaa

there is a DNS entry for:
wrokflw.svc.cmdaa

the actual server that is running the service is:
spackler

with K8s ingress, the domain will never match up with the actual servers running the service.

**Comment by doriordan** [comment] 2019-01-16 10:37
Closing this as could not reproduce

**Closed by doriordan** 2019-01-16 10:37 UTC
