### ISSUE TITLE
[Meta Issue] Namespaces behaviour

### ISSUE THREAD

**Issue by ngortheone** [doriordan/skuber#201] opened 2018-08-27 17:01 UTC
Inspired by #192 - I was thinking about the right approach and I bumped into a number of problems: So I decided to get my thoughts out here to discuss and get more opinions.

Starting from the beginning: when using kubectl there are roughly 3 ways to set namespace that work in a hierarchy:
- Level 1 - Kubectl configuration - whatever is set in your current kubeconfig file context, or “default” if nothing is set. This is analogous to skuber's `RequestContext` 
  ```scala
  @ k8s.namespaceName
  res5: String = "ns-1
  ```
- Level 2 - Explicitly set namespace in a resource definition that is being created/modified. This overrides Level 1
- Level 3 - Command line argument `—namespace` passed to kubectl - has the highest priority, explicitly submits given resource to a given namespace. If namespace in metadata of the resource is different from explicitly passed namespace - an error will be issued
`the namespace of the provided object does not match the namespace sent on the request`  

### Problems:
Skuber currently supports level 1 - client level configuration. Level 2 - behavior is not obvious and may even me inconsistent. Level 3 - most likely does not exist et the moment (and not sure if we need it)

#### level 1
Using only level 1 setting is not always convenient, but it should be possible to get the job done.
Like:
```
`k8s.usingNamespace(“anothernamespace”).create(mything)`
```
With one condition though - you should not specify the namespace in your resource.
Bug:  #202 

And the thing that is unclear for me here - do you need explicitly close the client that was spawned with `k8s.usingNamespace`or not? (To avoid thread leaks for example)

#### level 2 
In addition to bug in level1, explicitly set namespace in a resource  causes 
```scala
Status(v1,Status,ListMeta(,),Some(Failure),Some(the namespace of the provided object does not match the namespace sent on the request),Some(BadRequest),None,Some(400))))
```
Meaning that the hierarchy `client < resource` is not honored
Bug: #204

And there are some non-bug challenges that make improvements difficult
- Creating convenience methods for resources like `withNamespace` is a bit difficult. Since RequestContext operates on abstract class level (`ObjectResource`) we can't use copy constructor to add this functionality to the base class. It is either copy-paste work to add this to each and every child of ObjectResource or dirty code like described [on stackoverflow](https://stackoverflow.com/questions/12370244/case-class-copy-method-with-superclass)
```
def getIt(f:Base)={ 
  (f.getClass.getConstructors.head).newInstance("yeah").asInstanceOf[Base]
}
```
I am not a scala guru, so if someone has more elegant solution to this problem - please share

- Many fields of `ObjectMeta` are set to `EmptyS` but they are optional in fact. (@doriordan at #192)
  > At the moment metadata.namespace is a String rather than an Option[String] and is set to "default" by default because that is the Kubernetes default. However perhaps it should be set to an empty string by default, and then that indicates it has not been explicitly set by the user as opposed to having been set explicitly to "default". My concern is whether this might break some existing code.

The difference is very small, but can lead to a really obscure bugs and strange behavior, which really depends on how kubernetes apiserver will treat empty string vs absent field in every case. I am not sure if we should leave this as is for now. 

####  Level 3 
Do we need it? It seems that all possible cases should be covered by working level 1 and 2

P.S. I will create issues mentioned above and link them here

**Comment by ngortheone** [comment] 2018-09-06 01:59
@doriordan I've been researching possible approaches on creating convenience methods like `withNamespace` and I am on a crossroads. 
The basic problem is that this requires abstraction over arity, 

There is number of ways we can do it:
* If we are brave and do not fear the copypaste - declare abstract method `def withNamespace(ns: String): ObjectResource` in ObjectResource and write 40+ implementations for every child. Something like `def withNamespace(ns: String): ObjectResource = copy(metadata=this.metadata.copy(namespace=ns))`
  + PROS: No additional dependencies, code is straightforward
  + CONS: not DRY, maintaining will be pain

* If we want to avoid repetition, and do not care about beauty. Basic idea is to use reflection to get access to case class constructor in a generic context/in parent abstract class. Example here -[Convenient updates for immutable objects in Scala](http://jayconrod.com/posts/32/convenient-updates-for-immutable-objects-in-scala)
  + PROS: No additional dependencies, avoid repetition
  + CONS: 
    - Implementation is ugly
    - Usage will be ugly too, especially if we want to to update fields that do not fall under AnyRef (like Int) - it will require explicit cast to Integer first.

* If we are just brave and living in today - use macros. There is a lib that provides that - [Updating immutable objects in generic contexts](https://blog.hablapps.com/2013/03/07/updating-immutable-objects-in-generic-contexts/), hosted on Github [here](https://github.com/hablapps/updatable)
  + PROS: No repetition, looks BnL Ok
  + CONS: 
    - Additional dependency 
    - Lib repo looks a bit abandoned
    - Macros will change a lot in Scala 3 which is creates a major concern for portability

* Be like cool kids, use [shapeless](https://github.com/milessabin/shapeless). I am still researching this option, but it should be doable based by information provided by @lJoublanc  - 
  > use shapeless.LabelledGeneric to convert your case classes into shapeless.HList records,
  > for which you can use shapeless.ops.record methods to modify the name field, returning a new HList.
  > Finally, you use LabelledGeneric to reverse steps 1 to get back to your original type.
  > This only works if your types have stable identifiers e.g. if they are all case classes.
  + PROS: No repetition,Shapeless is an actively maintained lib that gives a promise to get rid of boilerplate code
  + CONS: Additional dependency, not sure what else


There is also always a way to do it Java style with mutation and var fields, but I don't think that this is really an option. One can use official java k8s client for that.

And lastly, the thought "What if we start generating code from kubernetes swagger and this problem will go away on its own?" is constantly reminding of all the manual things we should not be doing in ideal word.

So not sure in which direction should I start digging.

**Comment by doriordan** [comment] 2018-09-06 08:27
Hi @ngortheone - this is a general limitation I ran into quite early when developing skuber. Part of the problem is that case classes can't inherit from other case classes (otherwise  we could just define a base object resource case class with the metadata and fluent methods on that metadata).

My own view now is that this can be done most cleanly and most generally - without modifying skuber i.e. application responsibility - by using typelevel libraries that have generic ways of handlign case classes. Shapeless offers opportunities, but I think lenses can be a nice and simple way to handle this. For example using https://github.com/adamw/quicklens:
```
import com.softwaremill.quicklens._

val defaultDeployment: Deployment = .. // deployment in default namespace
val myDeployment = defaultDeployment.modify(_.metadata.namespace).setTo("mynamespace")
```
which I think is nice and simple and means we don't have to add lots of complexity or repetitive bolierplate to skuber. 

Lenses also work very well for other skuber use cases such as modifying certain fields of deeply nested pod or other specs.

If this seems a sensible approach, then I think this issue could be turned into a document/example exercise where we add an example (or extend existing fluent methods example) to show some applications of lenses for modifying object resources, and add a paragraph or two to the programming guide.

Thoughts welcome...

**Comment by doriordan** [comment] 2019-01-16 10:32
I've been looking at this for a different use case recently, and came up with some fairly simple code using Shapeless to address this mind of requirement (in this use case it was to modify metadata, but same general solution):
```
import shapeless._
import ops.record._

import skuber.{ObjectResource, ObjectMeta, OwnerReference}

object GenericResourceModifiers {

  type MetadataModifier[R <: HList]=Modifier.Aux[R, Witness.`'metadata`.T, ObjectMeta, ObjectMeta, R]

  def withMetadata[O <: ObjectResource, R <: HList](obj: O, metadata: ObjectMeta)(implicit
    generic: LabelledGeneric.Aux[O, R],
    modifier: MetadataModifier[R]): O =
  {
    val rec = generic.to(obj)
    val updatedRec = modifier(rec, _ => metadata)
    generic.from(updatedRec)
  }
}
```
so we can now call `withMetadata` to update the metadata on any object resource type

**Comment by doriordan** [comment] 2019-08-23 09:05
Closing this as proposals above seem reasonable and do't require skuber changes

**Closed by doriordan** 2019-08-23 09:05 UTC
